stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: production
  GOOGLE_CLOUD_API_CLIENT_ID: $GOOGLE_CLOUD_API_CLIENT_ID
  GOOGLE_CLOUD_API_CLIENT_SECRET: $GOOGLE_CLOUD_API_CLIENT_SECRET
  GOOGLE_CLOUD_API_REFRESH_TOKEN: $GOOGLE_CLOUD_API_REFRESH_TOKEN
  EXTENSION_ARTIFACT_ID: $EXTENSION_ARTIFACT_ID
  EXTENSION_PROJECT_FOLDER: .

default:
  image: node:22
  before_script:
    - npm install

build:
  stage: build
  script:
    - echo "Build concluído" # Substitua por um build real se necessário
  only:
    changes:
      - "**/*"

test:
  stage: test
  parallel:
    matrix:
      - NODE_VERSION: "22"
      - NODE_VERSION: "20"
      - NODE_VERSION: "18"
  image: node:${NODE_VERSION}
  script:
    - npm test
    - npm run test:ci-cd
  only:
    changes:
      - "**/*"

deploy:
  stage: deploy
  script:
    - npm run build
    - npm run bundle
    # - npm run deploy
    - npm run deploy:no-project
  only:
    - main
  except:
    - "*.md"
